# https://docs.npmjs.com/trusted-publishers
name: NPM Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write # required for OIDC trusted publishing
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: Determine npm tag
        id: npm-tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          # Update this condition when bumping the major version!
          if [[ $TAG == v1.7.* ]]; then
            echo "tag=old-version" >> $GITHUB_OUTPUT
          elif [[ $TAG == *-rc* ]]; then
            echo "tag=rc" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        run: npm publish --tag ${{ steps.npm-tag.outputs.tag }}
